# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities


class TestMimosHomepage():
    def setup_method(self, method):
        self.driver = webdriver.Firefox()
        self.vars = {}

    def teardown_method(self, method):
        self.driver.quit()

    def test_mimos_home(self):
        self.driver.get("https://www.mimos.my/main/")
        self.driver.maximize_window()
        time.sleep(5)
        # Scrolling
        element = self.driver.find_element(By.CSS_SELECTOR, ".top_padding_phone_8vw")
        self.driver.execute_script("arguments[0].scrollIntoView(true);", element)
        time.sleep(2)
        # screenshot
        self.driver.get_screenshot_as_file("D:\\Training\\Demo\\pythonProject\\screenshots\\mimos-home.png")
        # Scrolling
        element = self.driver.find_element(By.XPATH, "//div[@id='more-features']")
        self.driver.execute_script("arguments[0].scrollIntoView(true);", element)
        time.sleep(1)

    def test_mimos_about_us(self):
        self.driver.get("https://www.mimos.my/main/")
        self.driver.maximize_window()
        time.sleep(5)
        # Mouse Over
        element_to_hover_over = self.driver.find_element(By.XPATH, "//span[normalize-space()='About Us']")
        hover = ActionChains(self.driver).move_to_element(element_to_hover_over)
        hover.perform()
        # click
        self.driver.find_element(By.XPATH, "//span[normalize-space()='The Leaders']")
        time.sleep(1)
        # screenshot
        self.driver.get_screenshot_as_file("D:\\Training\\Demo\\pythonProject\\screenshots\\about-us-leaders.png")
        time.sleep(1)
