# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities


class TestMimosHomepage():
    def setup_method(self, method):
        self.driver = webdriver.Firefox()
        self.vars = {}

    def teardown_method(self, method):
        self.driver.quit()

    def test_mimos_innovation(self):
        self.driver.get("https://www.mimos.my/main/")
        self.driver.maximize_window()
        time.sleep(5)
        # Mouse Over
        element_to_hover_over = self.driver.find_element(By.XPATH, "//span[normalize-space()='Innovation']")
        hover = ActionChains(self.driver).move_to_element(element_to_hover_over)
        hover.perform()
        # click
        self.driver.find_element(By.XPATH, "//span[normalize-space()='Research Excellence']")
        time.sleep(1)
        # screenshot
        self.driver.get_screenshot_as_file("D:\\Training\\Demo\\pythonProject\\screenshots\\innovation_research.png")
        time.sleep(1)
